### ISSUE TITLE
Doesn't work when vim's current directory isn't the same as the test's file directory.

### ISSUE THREAD

**Issue by donvargax** [alfredodeza/pytest.vim#11]
When you run Pytest on a file in a different directory than the current working directory, pytest shows the following message:

"No failed tests from a previous run"

If I change the current directory to the one where the test file is, everything works correctly.

**Comment by ev-agelos** [comment]
My structure is:
My project/
    - app1/
        - tests/
            -unit/
                -test_something.py
            -functional/
                -test_something_else.py
    -app2/....

I am on directory my_project/app1 and open the file tests/function/test_something.py
I run :Pytest function and shows green bar with all tests passed and then i type :Pytest session and shows the error!

When i move directory to my_project/app1/tests and open the functional/test_something.py works as expected.

**Comment by alfredodeza** [comment]
@ev-agelos please open a separate issue for this describing what errors you see and if possible a way to replicate. This particular ticket has been closed for a while and does not look related to what you are describing. Thanks!
