### ISSUE TITLE
py.test -s with conque doesn't clean up the buffer

### ISSUE THREAD

**Issue by ryanpetrello** [alfredodeza/pytest.vim#19]
When debugging with conque, subsequent debug sessions show the output from the previous debugging session:

http://showterm.io/2c8d47146ac15b65be8f0

**Comment by alfredodeza** [comment]
fixed in commits ac3b9448877d29f309e7cbfee1ac1a84ead98a84 and b5a97f6ef815ec80898b1315af2dba76126af627

Sorry for the delay :(
