### ISSUE TITLE
Can't run function/method that uses parametrization

### ISSUE THREAD

**Issue by sloria** [alfredodeza/pytest.vim#23]
### To reproduce:

Given the following code:

```python
import pytest

@pytest.mark.parametrize(('inp', 'expected'),
[
    ('2 + 2', 4),
    ('0 + 0', 0),
    ('2 + 2.0', 4.0),
])
def test_adding(inp, expected):
    assert eval(inp) == expected
```

Executing `:Pytest function verbose` results in the following error.

```
============================================================================================ test session starts ============================================================================================
platform darwin -- Python 3.4.2 -- py-1.4.26 -- pytest-2.6.4 -- /Users/sloria/miniconda/envs/fresh/bin/python3
plugins: xdist
collecting ... 
=============================================================================================  in 0.01 seconds ==============================================================================================
ERROR: not found: /Users/sloria/projects/python-projects/t.py::test_adding
(no name '/Users/sloria/projects/python-projects/t.py::test_adding' in any of [<Module 't.py'>])
```

Note: `:Pytest file` works fine. However, it'd be very nice to run paramerized test functions and methods in isolation.

**Comment by sloria** [comment]
@alfredodeza The patch works as expected. I was able to run parametrized tests, but tests whose names begin with the same substring also run. For me, this is fine for the time being until the pytest issue you reported is addressed; better to have too many tests run than none. =)

**Comment by sloria** [comment]
To amend my previous comment: I ended up reverting back to `master`... turns out I name my test functions with the same prefix more often than I thought. 

Hopefully there's a better solution that doesn't add too much complexity.

**Comment by alfredodeza** [comment]
Even though that is the case for you, I think this plugin should still try to work with parametrized tests vs. not handling them at all. I will merge this into master shortly unless you have strong opinion against it?

I've been bit by this problem before and I rather have a few extra tests run (in the worse case scenario) than just a generic error.

**Comment by sloria** [comment]
@alfredodeza I think it is fine to merge. I have no strong opinion either way.

**Comment by asafpelegcodes** [comment]
If I did a pip install --upgrade will I be able to see the bug fixed, I'm currently experiencing the same issue

**Comment by alfredodeza** [comment]
@asafpelegcodes this issue is from `py.test` and has not been fixed. This branch fixes this problem in the sense that it applied a filter option (with `-k`) so you should be able to run parametrized tests and not see an error.

py.test issue is here: https://bitbucket.org/hpk42/pytest/issue/649/parametrized-test-nodes-cannot-be

**Comment by asafpelegcodes** [comment]
Thanks Alfredo, I just commented on the bitbucket bug as well to note that
I found it as well.
