### ISSUE TITLE
Fails with spaces in file path

### ISSUE THREAD

**Issue by alexlafroscia** [alfredodeza/pytest.vim#32]
Apparently `pytest.vim` has trouble running tests that have a space in the path to the current directory; `pytest` itself doesn't have this problem if run from the command line.

**Comment by alfredodeza** [comment]
Give me some time to replicate this and I will get back to you soon. Thanks for reporting this!

**Comment by alexlafroscia** [comment]
Sure thing :smile:

**Comment by alfredodeza** [comment]
@alexlafroscia I tried replicating the issue and couldn't. Would you mind setting up something that I can use to replicate the issue? I tried different spaces in the path and was not able to trigger any problems

**Comment by alexlafroscia** [comment]
Yeah, I'll try to put something together.

**Comment by alexlafroscia** [comment]
Alright, so if you unzip this file, open `main.py` in Vim and then run `Pytest project`, I got an error.  If I then check out `Pytest session` for more details, it says that there is no directory called `path/to/location/failing`.

http://d.pr/f/15Akp

**Comment by alfredodeza** [comment]
It seems this only affects `project` and nothing else. Can you confirm this on your end? I wasn't able to make it break with function/file/class/method

**Comment by alfredodeza** [comment]
@alexlafroscia I just pushed 66135d96689b5f7a4211f208d0a83bf83b23523e to master, would you mind updating the plugin and see if that fixes it? I tested locally without problems.

**Comment by alexlafroscia** [comment]
Yup, seems to be fine now! Thanks!
