### ISSUE TITLE
Running :Pytest file fails on files with spaces in their paths

### ISSUE THREAD

**Issue by D-Vaillant** [alfredodeza/pytest.vim#40]
On Windows 10, GVim:
`ERROR: file not found: C:\Users\David`
File is located at `C:\Users\David Vaillant\Programming\etc\etc.py`.

Seems like it's a space-escaping issue?

**Comment by alfredodeza** [comment]
@D-Vaillant can you try using commit f76b2010ca486f54ec23b5f00cb511247d9196cf (in escaped-paths branch) and see if that fixes your problem? Thanks!

**Comment by D-Vaillant** [comment]
I switched to using commit `f76b201` but no change.

**Comment by alfredodeza** [comment]
@D-Vaillant can you try that actual branch? I found an issue with my one commit (and pushed 8245c63df5cbd0344f0f133542d970d170752ff4 )

**Comment by D-Vaillant** [comment]
Seems like that did it!
