### ISSUE TITLE
Why not feed the location list with the errors found?

### ISSUE THREAD

**Issue by josefson** [alfredodeza/pytest.vim#45]
I know you implemented next/previous/first/last functions, so this is more a doubt question than anything else. What was the reason behind the choice made here in that regard.

**Comment by alfredodeza** [comment]
Interesting! I had no idea about location list. I always disliked the Quickfix window because it was global. If you had a way to implement this it would be nice

**Comment by josefson** [comment]
I don't know any vimscript, i just liked your plugin a little up to the point where i had to map the jumps to the same bindings i have for location-list movements, but then it could cause me pain when i have a location-list and your buffer opened. I chose to use pytest with Dispatch for now, since i can't do much more, i describe bellow what i found about how to do it.
From what i read on the [documentation](http://vimdoc.sourceforge.net/htmldoc/quickfix.html), there are these 3 commands which expect an ```errorfile```:
```:lfile [errorfile]``` - Read and jump to 1st error.
```:lgetfile [errorfile]``` - Read and don't jump to 1st error.
```:laddfile [errorfile]``` - Add errors from errorfile to the current list, if there isn't any a new list is created.
With that in mind it is also relevant that ```errorfile``` expects a [error-file-format](http://vimdoc.sourceforge.net/htmldoc/quickfix.html#error-file-format).

**Comment by alfredodeza** [comment]
Thanks for the extra information. Sorry to hear that this caused you to use something else
