### ISSUE TITLE
Use ipdb or ipython capabilities when available.

### ISSUE THREAD

**Issue by decko** [alfredodeza/pytest.vim#49]
ipdb uses ipython terminal capabilities to let developers interact with python code at a breakpoint. It would be nice to use it instead pdb if it's available.

**Comment by alfredodeza** [comment]
One can use ipdb or anything really, you just need to pass the `-s` option when running. For example in a test method that has `import ipdb; ipdb.set_trace()` you can do this:

    :Pytest method -s

And it will drop to a shell with ipython. Do you mean something different? Does the example not work for you?

**Comment by decko** [comment]
Sorry @alfredodeza. I didn't read the docs. It works here with ipdb.

But when I have a split on the window, after the -s or --pdb exits it close the split where it ran. It's the expected behavior?

**Comment by alfredodeza** [comment]
@decko if the process exits so will the window. If you want to keep it around, don't exit. Closing this now since this is not really a bug. Feel free to re-open if you encounter a problem
