### ISSUE TITLE
Broken on Neovim stable

### ISSUE THREAD

**Issue by decko** [alfredodeza/pytest.vim#50]
Neovim 0.2 is the new stable, but pytest.vim won't work there.
It's there a easy way to update it?

**Comment by alfredodeza** [comment]
Is this the same issue as https://github.com/alfredodeza/pytest.vim/issues/47 ?

**Comment by decko** [comment]
Yes it is. Should I close this issue and focus on #47?

**Comment by alfredodeza** [comment]
Yep, thanks for reporting. Anything that you can add to that other issue would be great (I am having issues trying to find a fix)
