### ISSUE TITLE
open terminal in new split for test

### ISSUE THREAD

**Issue by jwkvam** [alfredodeza/pytest.vim#51]
Very nice plugin! Is it possible to run a test in a neovim terminal in a different window/split? I like to run with "-s" sometimes but when I do it reuses the split which contains the code I'm trying to test.

I managed to hack something myself. Maybe it'd be nice to have a config option? :)
```
    if has('nvim')
        exe ":vsp term://" . pdb_command
        exe ":startinsert"
    else
```

**Comment by alfredodeza** [comment]
Yeah, when I was using neovim this was very annoying, I would have to split first and then run my test, every time.

I'm inclined to say this is a problem with neovim (it is fine in vim). The problem with `vsp` is that a user might not want `vsp` and might prefer a horizontal split (`sp`) or to place a split in some other fashion (to the left, or the right, etc...)

**Comment by alfredodeza** [comment]
If using Vim 8, you get the full terminal support with correct window placement. I'm no longer using NeoVim and it is hard for me to support it now.
