### ISSUE TITLE
Consider allowing setting the debugger

### ISSUE THREAD

**Issue by Alok** [alfredodeza/pytest.vim#52]
I'm sure many people use `pudb` or `ipdb` instead of regular `pdb` because it's not great.

**Comment by alfredodeza** [comment]
Can you explain a bit more what you are trying and how that isn't working? There is no specific support for `pdb`. I personally use `ipdb` and that works fine with pytest.vim

This is supported by using the "no capture" flag, like:

    :Pytest method -s

Which will allow to drop to the debugger (regardless of your choice).

**Comment by alfredodeza** [comment]
Closing this as I believe it is a non-issue. Feel free to-reopen in case you are finding this is not working correctly. Thanks!
