### ISSUE TITLE
Support to run on save

### ISSUE THREAD

**Issue by atgiovannini** [alfredodeza/pytest.vim#53]
Could be a nice feature to enable `run test` when project file saved. And maybe some little box green/red for fail or pass all tests instead resume of all test (optional color box)

**Comment by alfredodeza** [comment]
There is already support for this with `looponfail` have you tried that and it doesn't work for your use case?

https://github.com/alfredodeza/pytest.vim/#looponfail

**Comment by atgiovannini** [comment]
Yes, I'm using this feature now, but when all tests are Passed, then not run again.

(And I'm getting some python exceptions on run on save)

**Comment by alfredodeza** [comment]
The problem with not stopping this behavior on some condition is that it can get annoying pretty fast.  You could set this for your use case with an autocommand without requiring the plugin to support it directly:

    :autocmd BufWritePost *.py :Pytest file

Closing this as the plugin supports the initial reported issue. For #20 that needs to get fixed there
