### ISSUE TITLE
:Pytest method not working

### ISSUE THREAD

**Issue by atgiovannini** [alfredodeza/pytest.vim#54]
On every try to execute `:Pytest method`  get `Unable to find a matching method for testing `

**Comment by alfredodeza** [comment]
This is because the call is "context aware". It depends on the position of your cursor searching backwards. In this case it should work:

    class TestFoo(object):
    
        def test_foo(self):
            assert True
        <cursor position here>

But this would not work:

    class TestFoo(object):
    
    <cursor position here>

        def test_foo(self):
            assert True

**Comment by alfredodeza** [comment]
If that is not the case, then could you show me some examples of the code you are trying to test and where your cursor is at the moment of invocation?

**Comment by atgiovannini** [comment]
I'm using pytest, and not defining class like with unit test, maybe is for that, I attach you a test file
[test_files.txt](https://github.com/alfredodeza/pytest.vim/files/1363067/test_files.txt)

**Comment by alfredodeza** [comment]
@atgiovannini you are using a function, not a class, so you would need to do:

    :Pytest function 

Alternatively, to run the whole file:

    :Pytest file

**Comment by atgiovannini** [comment]
Yeah, I'm using `:Pytest file` now, and I'm sorry, I didn't read about `:Pytest function`  in README. 
Then, can close issue ;)
