### ISSUE TITLE
"Undefined variable: a:3" during looponfail run

### ISSUE THREAD

**Issue by OddBloke** [alfredodeza/pytest.vim#62]
When running with `:Pytest class looponfail`, I see an error when I save the test file:

![vim-pytest](https://user-images.githubusercontent.com/62736/36613763-86adc7ae-18a8-11e8-9f14-76982e4d83f7.png)

This doesn't, AFAICT, actually affect the running of the tests.

**Comment by alfredodeza** [comment]
I just pushed db2daea041e88d3a5aadd5d79fab8f27f35e9c32 which should fix this. Can you verify it works for you ?

Thanks for reporting this!

**Comment by OddBloke** [comment]
This has removed that particular error; I'm now observing tests run every time I save, but I'll open a separate issue for that.

Thanks for the quick fix!
