### ISSUE TITLE
Configurable project test directory

### ISSUE THREAD

**Issue by vecin2** [alfredodeza/pytest.vim#74]
Great plugin, simple and work OTB prefect! 
I just had to tweak slightly to make it work for my requirements:
I am working within a project which has multiple 'tests' directories, so I needed to customize the directory used to project tests. 
I was able to after adding a line to my `.vimrc`:
`let g:pytest_test_dir='/my/python/project/root'`

And then adding an additional if to your script so that var didn't get overridden:
```
if !exists("g:pytest_test_dir")
	let g:pytest_test_dir          = 'tests'
endif
```
I could submit a pull request, but I am sure you could implement this requirement in a much nicer way :)

**Comment by alfredodeza** [comment]
That is a good catch. I still struggle with the feature of being able to run all the tests in a project (I don't think it is a good idea to run them all inside Vim), but I agree that this variable shouldn't get overridden.

Thank you for the code suggestion, and after reviewing the plugin, I think that would be fine as a PR (to give you credit). If you prefer for me to make the changes, I'm happy to do that as well. Let me know!

**Comment by vecin2** [comment]
Hi Alfredo!
Congrats on this project. I've initially started using vim-test, but I had
to play around with settings to get working close to what I wanted. Then,
I've tried yours: its simple and straight to the point, like it!

I'll submit a pull request hopefully can make it this weekend.

One more thing, could you elaborate more on why is a bad idea to run all
project tests within vim?

Thanks
David

**Comment by alfredodeza** [comment]
Here are a few reasons that are concerning to me:

* Running all the tests for a project might take a while. The idea behind running tests in a text editor is fast feedback - the complete opposite of running all the tests in a project
* The `tests/` directory might have functional tests that might not be desirable, and it is really hard to exclude from the plugin
* There is potential for several dozens (even hundreds!) of test failures, which again, defeats the purpose of running a test in the editor.

The `project` testing was a contribution, which I hesitated a lot to get in. But I'm happy that users like you find it great - I just never use it.

**Comment by alfredodeza** [comment]
Fixed with https://github.com/alfredodeza/pytest.vim/pull/75
